-- MySQL Script generated by MySQL Workbench
-- 04/24/15 11:23:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zrecommender
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zrecommender` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zrecommender` ;

-- -----------------------------------------------------
-- Table `zrecommender`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zrecommender`.`movie` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(200) NULL,
  `genres` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
